### ISSUE TITLE
SyntaxError: Unexpected token { in JSON at position 145

### ISSUE THREAD

**Issue by RevivedSol** [jacobtruman/nodejs_steambot#19]
This the whole error code 

SyntaxError: Unexpected token { in JSON at position 145
    at Object.parse (native)
    at Object.<anonymous> (C:\Users\JingYong-PC\Desktop\nodejs_steambot-master\trade_offers.js:114:16)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

What is wrong here ? 

// main config file
if (fs.existsSync(configFile)) {
    var data = fs.readFileSync(configFile, 'utf8');
    if (data != undefined){ 
 config = JSON.parse(data);
}else {
        throw Error("MISTAKE: there was a problem reading the config file: " + configFile);
    }
} else {
    throw Error("MISTAKE: configFile does not exist: " + configFile);
}

And if possible can someone add me on steam or facebook and teach me how to install it properly

**Comment by jacobtruman** [comment]
@RevivedSol, could you provide the command you are using to run the bot?

**Comment by RevivedSol** [comment]
Node trade_offers.js

**Comment by jacobtruman** [comment]
You need to create a config file containing your user information:
https://github.com/jacobtruman/nodejs_steambot/wiki

**Comment by RevivedSol** [comment]
Ive already done it though, even made a folder named configs and put it in there

**Comment by jacobtruman** [comment]
As it says on the wiki `node trade_offers.js username`, where username is the name of the config file you created.

**Comment by RevivedSol** [comment]
Huh ?  So i should do node trade_offers.js config. ?

**Comment by RevivedSol** [comment]
Will try, will get back to you if there is still any issues

**Comment by RevivedSol** [comment]
@jacobtruman Hmm i try reinstalling the bot and after i type npm install nodejs_steambot ,  it says "50 error Refusing to install nodejs_steambot as a dependency of itself"

**Comment by jacobtruman** [comment]
How did you go about uninstalling the bot?

**Comment by RevivedSol** [comment]
@jacobtruman what do you mean ? and i can only download the depencies using npm install

**Comment by jacobtruman** [comment]
what did you do to uninstall it? what command did you run, or what exactly did you delete?

**Comment by RevivedSol** [comment]
i deleted everything and redownload at github, the previous one's depencies were also installed using npm install

**Comment by jacobtruman** [comment]
Delete everything again and run `npm install nodejs_steambot`

https://www.npmjs.com/package/nodejs_steambot

**Comment by RevivedSol** [comment]
It gave me this error

npm ERR! Windows_NT 10.0.15063
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "nodejs_steambot"
npm ERR! node v6.10.2
npm ERR! npm  v3.10.10
npm ERR! code ENOSELF

npm ERR! Refusing to install nodejs_steambot as a dependency of itself
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\JingYong-PC\Desktop\nodejs_steambot-master\npm-debug.log

**Comment by RevivedSol** [comment]
have you found the fix ? @jacobtruman

**Comment by jacobtruman** [comment]
I have never run into this problem and I am inclined to think it is an issue with how npm works, and not my code. Could you try running the install in a different directory?

**Comment by RevivedSol** [comment]
is it something to do with the version of my nodejs ?

**Comment by jacobtruman** [comment]
Not sure - a quick google search might help:

https://www.google.com/search?q=Refusing+to+install+as+a+dependency+of+itself&oq=Refusing+to+install+as+a+dependency+of+itself&aqs=chrome..69i57j0l5.3949j0j7&sourceid=chrome&ie=UTF-8

http://stackoverflow.com/questions/11940086/refusing-to-install-sqlite3-as-a-dependency-of-itself

**Comment by RevivedSol** [comment]
kudos to this, it started downloading the dependices

Check if your project folder name is same as the module you are trying to install,

If you try to install express inside a project folder name express, you will get this error.

Rename your Project Folder, Your project Folder name should be unique compared to the npm module names

Also change the package.json file entry

 "name": "xxxxx",
  "version": "1.0.0",

**Comment by jpumford** [comment]
This is because you are running `npm install nodejs_steambot` inside the steambot directory itself. If you run `npm install [package]`, it will install `[package]` in the `node_modules` subdir

Run `npm install` instead of `npm install nodejs_steambot`

**Comment by RevivedSol** [comment]
now...

Error: Cannot find module 'steam-webapi

mm

**Comment by jpumford** [comment]
Are you running just `npm install` in the base directory? Which command spits out this error? `steam-webapi` installs fine for me.

**Comment by RevivedSol** [comment]
first i do this at cmd 
"cd C:\Users\JingYong-PC\Desktop\nodejs_steambot-master"

Then i typed
npm install

And i type
node trade_offers.js

**Comment by jpumford** [comment]
@jacobtruman it looks like this might be due to the dependency being namespaced under @doctormckay, but it's required in as just `steam-webapi` and not `@doctormckay/steam-webapi`.

Did this dependency change recently? It could be you still have a local copy of `steam-webapi` so it's not failing for you.

**Comment by jacobtruman** [comment]
@jpumford I am not sure, I have been using without issue for more than a year. My last update (which was unrelated to `steam-webapi`) was 22 days ago.

**Comment by RevivedSol** [comment]
@jacobtruman is it possible that you give me a copy of yours ? Like maybe upload to mediafire or any link

**Comment by jacobtruman** [comment]
It looks like I am running on version 0.6.5 of `steam-webapi`, which might explain that.

**Comment by RevivedSol** [comment]
@jacobtruman  ive download the 0.6.5 version but now another issue -_-

C:\Users\JingYong-PC\Desktop\nodejs_steambot-master\node_modules\tfprices\index.js:8
        p.key = options.key;
                       ^

TypeError: Cannot read property 'key' of undefined
    at new tfprices (C:\Users\JingYong-PC\Desktop\nodejs_steambot-master\node_modules\tfprices\index.js:8:17)
    at Object.<anonymous> (C:\Users\JingYong-PC\Desktop\nodejs_steambot-master\trade_offers.js:155:14)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by jpumford** [comment]
I get that error as well. What does `npm ls | grep tfprices` give you @jacobtruman?

**Comment by jacobtruman** [comment]
The fix is quite simple... `node index.js username`; the `trade_offers.js` file is old - I need to update the wiki.

**Comment by RevivedSol** [comment]
@jacobtruman in anyway you need help ? :D

**Comment by RevivedSol** [comment]
@jacobtruman  so ive download the new one and where should i put my is and ss ? 

C:\Users\JingYong-PC\Desktop\tf2 bot\index.js:443
        if(account_config.steam_guard.shared_secret != undefined) {
                                     ^

TypeError: Cannot read property 'shared_secret' of undefined
    at getLogonOptions (C:\Users\JingYong-PC\Desktop\tf2 bot\index.js:443:31)
    at Object.<anonymous> (C:\Users\JingYong-PC\Desktop\tf2 bot\index.js:132:20)
    at Module._compile (module.js:570:32)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.runMain (module.js:604:10)
    at run (bootstrap_node.js:393:7)
    at startup (bootstrap_node.js:150:9)

**Comment by jacobtruman** [comment]
That all should be auto generated and written to the config file after you put in your steam guard code.

**Comment by RevivedSol** [comment]
I cant even login though, it straight away show that error. And btw which smaple config should i use ? The one with custom sel/buy order or the one needed bp.tf api ?

**Comment by RevivedSol** [comment]
@jacobtruman i still couldnt login, it keeps showing the error and wont let me type my steamguard code

C:\Users\JingYong-PC\Desktop\tf2 bot\index.js:443
if(account_config.steam_guard.shared_secret != undefined) {
^

TypeError: Cannot read property 'shared_secret' of undefined
at getLogonOptions (C:\Users\JingYong-PC\Desktop\tf2 bot\index.js:443:31)
at Object. (C:\Users\JingYong-PC\Desktop\tf2 bot\index.js:132:20)
at Module._compile (module.js:570:32)
at Object.Module._extensions..js (module.js:579:10)
at Module.load (module.js:487:32)
at tryModuleLoad (module.js:446:12)
at Function.Module._load (module.js:438:3)
at Module.runMain (module.js:604:10)
at run (bootstrap_node.js:393:7)
at startup (bootstrap_node.js:150:9)

**Comment by jacobtruman** [comment]
What command are you using to start the bot?

**Comment by RevivedSol** [comment]
Node index.js config

**Comment by jacobtruman** [comment]
You need both `config.json` and `username.json`, where username is your username. Then your command should be `node index.js username` where username is your username. For example: my username is jacobtruman, so the command I run is `node index.js jacobtruman`.

**Comment by RevivedSol** [comment]
Ops forgot to tell you ive tried that too :c

**Comment by jacobtruman** [comment]
Ok, post your configs here - make sure you change passwords one keys.

**Comment by RevivedSol** [comment]
ok ive tried put both with the same thing 

{
	"username":"*******",
	"password":"******",
	"bot":
	{
		"item":"ITEM TO BE BOUGHT/SOLD",
		"purchase_price":0,
		"sale_price":0
	}
}

ive also tried setting the config.json to the default one 

{
	"username":"USERNAME",
	"password":"PASSWORD",
	"bot":
	{
		"item":"ITEM TO BE BOUGHT/SOLD",
		"purchase_price":0,
		"sale_price":0
	}
}

**Comment by RevivedSol** [comment]
@jacobtruman anything wrong with the config ?

**Comment by jacobtruman** [comment]
I am assuming your username is not *, and that you put your actual password in.

**Comment by RevivedSol** [comment]
Huh ? I dont get it ...

**Comment by jacobtruman** [comment]
What is the username you use to login to steam? That is what should be in the username field. The password you use to login to steam should go in the password field. The config you posted has "*" for the username. I don't want you to post your password here, but it should be in your config file.

**Comment by RevivedSol** [comment]
thats what i did though :c

**Comment by RevivedSol** [comment]
@jacobtruman    add me on steam   steamcommunity.com/id/tokenboi    i think its easier and safer

**Comment by RevivedSol** [comment]
Or maybe skype? Ill share my screen

**Comment by jacobtruman** [comment]
Ok, there is more that I need to document about how to setup your config - there are a few things generated when enabling steam guard that are not shown to you on your mobile device that need to be captured and added to the user config. I thought I had automated this in my script, but must not have. The problem with handling it automatically with the script is that you will no longer be able to use the steam guard codes generated on your mobile device. I will update the documentation that describes how to set this up for both your mobile device and the bot.

Stay tuned...

**Comment by RevivedSol** [comment]
So its the scripts' problem?

**Comment by jacobtruman** [comment]
No, it's a problem with your config

**Comment by RevivedSol** [comment]
Hmm, let do it through skype screen share

**Comment by RevivedSol** [comment]
@jacobtruman my skype is Lee Jing Yong and the location is semenyih, malaysia

**Comment by RevivedSol** [comment]
@ ok ive try doing the config again

config.json

{
	"username":"my username",
	"password":"my pass",
	"bot":
	{
		"item":"ITEM TO BE BOUGHT/SOLD",
		"purchase_price":0,
		"sale_price":0
	}
}

abc.json

{
	"username":"my username",
	"password":"my pass",
	"bot":
	{
		"item":"123",
		"purchase_price":0.11,
		"sale_price":0.11
	}
}


it still returns the same error

**Comment by RevivedSol** [comment]
ive also tried

config.json (default from sample_userconfig.json nothing changed)

{
	"username":"USERNAME",
	"password":"PASSWORD",
	"bot":
	{
		"item":"ITEM TO BE BOUGHT/SOLD",
		"purchase_price":0,
		"sale_price":0
	}
}

abc.json

{
	"username":"my username",
	"password":"my pass",
	"bot":
	{
		"item":"123",
		"purchase_price":0.11,
		"sale_price":0.11
	}
}

**Comment by jacobtruman** [comment]
I won't be doing a screen share; try disabling steam guard on your mobile device and running `node auth.js username` - that should give you what you are missing in your config.

**Comment by RevivedSol** [comment]
Nuuu i dont want 7 days trade ban

**Comment by RevivedSol** [comment]
@jacobtruman   ok ive tried it without disabling my steam guard and it returns this

Logged into Steam as [U:1:640368366]
{"status":29}
Invalid response - try again later

**Comment by jacobtruman** [comment]
You will need to disable the steam guard on your mobile device to get the info you need for the bot to work; yes, you will get the 7 day trade ban, but it will not work without it. If you want to use both the bot and your mobile device, you will either have to wait for me to update the wiki, or try to figure it out by trial and error.

**Comment by RevivedSol** [comment]
Can i see your config file ? :V  that could help

**Comment by jacobtruman** [comment]
That would not help, the info/secrets provided by steam guard is specific to my account - you need the info provided for your account.

**Comment by RevivedSol** [comment]
I have it, i know how to extract it c: clear your ss, is , username, and pass and show me your config

**Comment by RevivedSol** [comment]
Ive helped people setup/get their is for bp.tf automatic. So yea...

**Comment by jacobtruman** [comment]
`{
	"username": "USERNAME",
	"password": "PASSWORD",
	"login_key": "LOGIN_KEY",
	"steamid": "STEAMID",
	"bot_item": {
		"item": "Earbuds",
		"defindex": "143"
	},
	"steam_guard": {
		"shared_secret": "SHARED_SECRET",
		"serial_number": "SERIAL_NUMBER",
		"revocation_code": "REVOKE_CODE",
		"uri": "otpauth://totp/Steam:USERNAME?secret=SECRET&issuer=Steam",
		"server_time": "SERVER_TIME",
		"account_name": "USERNAME",
		"token_gid": "TOKEN_ID",
		"identity_secret": "IDENTITY_SECRET",
		"secret_1": "SECRET_1",
		"status": 1
	}
}`

**Comment by RevivedSol** [comment]
@jacobtruman  it working now :D   can i help you editing the readme.md or make a yt video on how to setup ?
