### ISSUE TITLE
Can you make buy and selling work again ? Please

### ISSUE THREAD

**Issue by DontAskM8** [jacobtruman/nodejs_steambot#22]
So, ive followed the link you gave -> https://github.com/jacobtruman/nodejs_steambot/blob/6ef0e748286068d81c1e4aea2a6d6a03311c16bd/trade_offers.js  for the `trade_offers.js`. I make a file named `trade_offers.js` and paste all the code in there, it returns `ReferenceError: prompt is not defined` a little googling solved the problem (adding ` var prompt = require('prompt');` into the code). But the next problem I have no idea how to solve.

i did `node trade_offers.js <username>` and it returns this and does nothing else, it wont accept incomming offers neither detect it like the `index.js`

<b>:: SUCCESS   :: Steam Client connected

:: SUCCESS   :: Attempting to logon bot for username

prompt: Steam Guard Code: :  RD8M5

:: SUCCESS   :: username logged on!</b>

After it shows this, nothing actually happens,

This is my `config.json`

``{
	"username": "USERNAME",
	"password": "PASSWORD",
	"login_key": "LOGIN_KEY",
	"steamid": "STEAMID",
	"backpacktf_key": "BACKPACK_KEY",
	"bot_item":{
		"item": "ITEM_NAME",
		"defindex": "DEFINDEX",
		"purchase_price": 0,
		"sale_price": 0
	},
	"steam_guard": 
		{
			"shared_secret": "SHARED_SECRET",
			"serial_number": "SERIAL_NUMBER",
			"revocation_code": "REVOKE_CODE",
			"uri": "otpauth://totp/Steam:USERNAME?secret=SECRET&issuer=Steam",
			"server_time": "SERVER_TIME",
			"account_name": "USERNAME",
			"token_gid": "TOKEN_ID",
			"identity_secret": "IDENTITY_SECRET",
			"secret_1": "SECRET_1",
			"status": 1 
		} 
}``

This is my `username.json`

`{
	"username": "abcde",
	"password": "abcde",
	"login_key": "1234",
	"steamid": "1234",
	"backpacktf_key": "1234",
	"bot_item": {
		"item": "Melee Slot Token",
		"defindex": "5014",
		"purchase_price": 0.11,
		"sale_price": 0.22
	},
	"steam_guard": {
		"shared_secret": "1234",
		"serial_number": "1234",
		"revocation_code": "1234",
		"uri": "otpauth://totp/Steam:1234?secret=7AIP3NRIC3NARXQ3R6JM6SFT63R73PLB&issuer=Steam",
		"server_time": "1234",
		"account_name": "1234",
		"token_gid": "1234",
		"identity_secret": "1234",
		"secret_1": "1234",
		"status": 1
	}
}`

**Comment by RevivedSol** [comment]
@jacobtruman

**Comment by jacobtruman** [comment]
I will probably re-add that functionality eventually, but I don't have the time to work on it right now...

**Comment by RevivedSol** [comment]
@jacobtruman  umm can you tell me how to use your node-tfprices ? Might wanna experiment with them

**Comment by jacobtruman** [comment]
It will not work without fixing the code - I removed the file because it is out of date.
